packages:
  - 'apps/*'
  - 'libs/*'
  - 'packages/*'

catalogs:
  react:
    react: ^18.3.0
    react-dom: ^18.3.0
  
  nextjs:
    next: ^15.0.0
    react: ^18.3.0
    react-dom: ^18.3.0
  
  fastify:
    fastify: ^4.25.0
    '@fastify/cors': ^8.5.0
    '@fastify/helmet': ^11.1.0
  
  tailwind:
    tailwindcss: ^3.4.0
    '@tailwindcss/vite': ^4.1.3
    postcss: ^8.4.47
    autoprefixer: ^10.4.20
  
  testing:
    vitest: ^1.0.0
    '@testing-library/react': ^14.1.0
    '@testing-library/jest-dom': ^6.1.0
